Jacob: issue #7617 - set_ylabel() doesn't work with AxesZeroSubplots. The problem was that AxesZeroSubplot() sets both axis to be instances of Xaxis. Thus, when the axes were being drawn it wouldn't look to the Yaxis to find the label. THe problem was in AxesZeroSubplot() not set_ylabel().

Nishant: issue #7194 - When adding an existing subplot into the AxesStack, an error is thrown due to an existing variable being of type Axes and the entry trying to be removed is of type tuple (key, Axes). According to the logic provided in figure.py, it should throw a warning and remove the previous entry.

Steven: Issue #8089 - Using Minute Locator to set x-axis ticks exceeds Locator.MAXTICKS, It seems like when you want to create more than 910 Elements in the date_list(their example) it causes the x-ticks to exceed 1000 and throw an error. The issue can be easily fixed by increasing the limit of the Constant variable but however the more recent code seems that it could create memory problems in the program.

Chandni: Issue #7460 (#7744) - Raise an appropriate ValueError if the limit set to set_xlim and set_ylim was out of bounds. Currently, the Value Error being raised is not much help as it only says “Unrecognized kwargs” (function line:2807 under ~/matplotlib/lib/matplotlib/axes/_base.py) whereas it would be beneficial to have meaningful ValueErrors (or better treat them as None so program doesn’t crash after execution).

Henry: Issue #7112 - It seems that shifts on the values in the axes cannot be set on the parallel direction to the respective axis. Eg. a shift vertically on a tick in the y axis does not register but a horizontal one will. The work-around suggested by a user was to manually define a lambda to change the axis coordinate. After a trace of the execution, I still could not pinpoint the exact location of the problem. However, the traces do hint at a possible sequence of calls in the wrong order being the cause of the issue.
